version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

volumes:
  dbdata: