version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./storage:/var/www/storage

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    restart: always
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

  postfix:
    image: catatnight/postfix
    restart: always
    environment:
      - "maildomain=${MAIL_DOMAIN}"
      - "smtp_user=${MAIL_USERNAME}:${MAIL_PASSWORD}"
